package com.corrodinggames.rts.game.units.custom.a;

import android.graphics.PointF;
import com.corrodinggames.rts.game.units.ao;
import com.corrodinggames.rts.game.units.a.t;
import com.corrodinggames.rts.game.units.a.u;
import com.corrodinggames.rts.game.units.custom.aj;
import com.corrodinggames.rts.game.units.custom.at;
import com.corrodinggames.rts.game.units.custom.bb;
import com.corrodinggames.rts.game.units.custom.bh;
import com.corrodinggames.rts.game.units.custom.bl;
import com.corrodinggames.rts.game.units.custom.bn;
import com.corrodinggames.rts.game.units.custom.h;
import com.corrodinggames.rts.game.units.custom.o;
import com.corrodinggames.rts.game.units.custom.v;
import com.corrodinggames.rts.game.units.custom.z;
import com.corrodinggames.rts.game.units.custom.a.e;
import com.corrodinggames.rts.game.units.custom.a.f;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.UnitReference$UnitReferenceOrUnitType;
import com.corrodinggames.rts.gameFramework.utility.m;

public class d {

   public int a;
   public String b;
   public String c;
   public aj d;
   public UnitReference$UnitReferenceOrUnitType e;
   public UnitReference$UnitReferenceOrUnitType f;
   public UnitReference$UnitReferenceOrUnitType g;
   public bb h;
   public aj i;
   public u j;
   public String k;
   public v l;
   public at[] m;
   public boolean n;
   public boolean o;
   public float p;
   public com.corrodinggames.rts.game.units.custom.d.b q;
   public com.corrodinggames.rts.game.units.custom.d.b r;
   public h s;
   public LogicBoolean t;
   public LogicBoolean u;
   public LogicBoolean v;
   public boolean w;
   public boolean x;
   public boolean y;
   public LogicBoolean z;
   public aj A;
   public LogicBoolean B;
   public aj C;
   public LogicBoolean D;
   public aj E;
   public LogicBoolean F;
   public LogicBoolean G;
   public v H;
   public v I;
   public v J;
   public boolean K;
   public boolean L;
   public boolean M;
   public boolean N;
   public boolean O;
   public boolean P;
   public boolean Q;
   public at[] R;
   public float S;
   public boolean T;
   public boolean U;
   public o V;
   public Float W;
   public boolean X;
   public boolean Y;
   public boolean Z;
   public bn aa;
   public com.corrodinggames.rts.game.units.custom.u ab;
   public m ac;
   public Float ad;
   public com.corrodinggames.rts.game.units.custom.d.b ae;
   public com.corrodinggames.rts.game.units.custom.d.b af;
   public Integer ag;
   public PointF ah;
   public LogicBoolean ai;
   public bh aj;
   public int ak;
   public ao al;
   public com.corrodinggames.rts.game.units.custom.b.g am;
   public LogicBoolean an;
   public LogicBoolean ao;
   public com.corrodinggames.rts.game.units.custom.u ap;
   public com.corrodinggames.rts.game.units.custom.u aq;
   public LogicBoolean ar;
   public z as;
   public z at;
   public bl au;
   public bl av;
   public bl aw;
   public bl ax;
   public com.corrodinggames.rts.gameFramework.m.e ay;
   public com.corrodinggames.rts.gameFramework.m.e az;
   public int aA;
   public LogicBoolean aB;
   public UnitReference$UnitReferenceOrUnitType aC;
   public boolean aD;
   public boolean aE;
   public LogicBoolean aF;
   public t aG;
   public LogicBoolean aH;
   public boolean aI;
   public int aJ;
   public boolean aK;
   public String aL;
   public f aM;
   public e aN;


   public d() {
      this.j = u.c;
      this.p = -999.0F;
      this.K = false;
      this.L = false;
      this.M = true;
      this.N = true;
      this.O = false;
      this.P = false;
      this.S = 0.01F;
      this.T = false;
      this.U = false;
      this.ac = new m();
      this.aG = t.d;
      this.aM = f.a;
      this.aN = e.a;
   }

   public String a() {
      return this.d != null?this.d.b():this.c;
   }
}
