package com.corrodinggames.rts.game.units.custom.logicBooleans;

import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$AmmoBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$AmmoIncludingQueuedBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$BuiltAmountBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$CompletedBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$CustomTimerBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$EnergyBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$EnergyIncludingQueuedBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$GameMapHeightBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$GameMapWidthBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$GameModeBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$HasActiveWaypoint;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$HasFlagDynamicBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$HasParent;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$HasResourcesBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$HasTakenDamage;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$HeightBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$HeightValueBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$HpBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$InMapBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$IsAttackingBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$IsControlledByAI;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$IsOnTeam;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$IsResourceLargerThan;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$IsReversingBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$KillsBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$LastConvertedBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$MaxEnergyBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$MaxHpBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$MaxMoveSpeedBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$MaxShieldBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$MovingBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$NumberOfAttachedUnitsBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$NumberOfConnectionsBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$NumberOfQueuedWaypoints;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$NumberOfUnitsInEnemyOrAllyTeam;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$NumberOfUnitsInTeam;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$OverCliftBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$OverLiquidBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$OverPassableTileBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$OverWaterBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$PositionXBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$PositionYBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$PriceCreditsBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$QueueSize;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$ResourceCountBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$RotationBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$ShieldBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$SpeedBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$SpeedValueBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$TagsBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$TeamDefeatedTechBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$TeamIdBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$TeamTagBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$TeamVictoryBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$TeamWipedOutBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$ThisActionRepeatedCount;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$TimeAliveBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$TouchWaterBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$TransportingCountBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$TransportingUnitWithTagsBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$UnitIdBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$isEnergyRechargingBoolean;
import com.corrodinggames.rts.game.units.custom.logicBooleans.LogicBooleanGameFunctions$isTransportUnloading;

public class LogicBooleanGameFunctions {

   static void addBooleanType(LogicBoolean var0, String ... var1) {
      LogicBoolean.addBooleanType(var0, var1);
   }

   static void loadTypes() {
      addBooleanType((new LogicBooleanGameFunctions$HeightBoolean()).with("underwater=true"), new String[]{"self.underwater", "self.isUnderwater"});
      addBooleanType((new LogicBooleanGameFunctions$HeightBoolean()).with("ground=true"), new String[]{"self.gound", "self.ground", "self.isAtGroundHeight"});
      addBooleanType(new LogicBooleanGameFunctions$HeightValueBoolean(), new String[]{"self.height", "self.z"});
      addBooleanType((new LogicBooleanGameFunctions$HeightBoolean()).with("flying=true"), new String[]{"self.flying", "self.isFlying"});
      addBooleanType(new LogicBooleanGameFunctions$MovingBoolean(), new String[]{"self.isMoving"});
      addBooleanType(new LogicBooleanGameFunctions$HasActiveWaypoint(), new String[]{"self.hasActiveWaypoint"});
      addBooleanType(new LogicBooleanGameFunctions$NumberOfQueuedWaypoints(), new String[]{"self.numberOfQueuedWaypoints"});
      addBooleanType(new LogicBooleanGameFunctions$SpeedValueBoolean(), new String[]{"self.speed"});
      addBooleanType((new LogicBooleanGameFunctions$SpeedBoolean()).with("atTopSpeed=true"), new String[]{"self.maxspeed", "self.isAtTopSpeed"});
      addBooleanType(new LogicBooleanGameFunctions$InMapBoolean(), new String[]{"self.isInMap"});
      addBooleanType(new LogicBooleanGameFunctions$TouchWaterBoolean(), new String[]{"self.inwater", "self.isInWater"});
      addBooleanType(new LogicBooleanGameFunctions$OverWaterBoolean(), new String[]{"self.overwater", "self.isOverwater"});
      addBooleanType(new LogicBooleanGameFunctions$OverLiquidBoolean(), new String[]{"self.isOverLiquid"});
      addBooleanType(new LogicBooleanGameFunctions$OverCliftBoolean(), new String[]{"self.isOverClift", "self.isOverCliff"});
      addBooleanType(new LogicBooleanGameFunctions$OverPassableTileBoolean(), new String[]{"self.isOverPassableTile"});
      addBooleanType((new LogicBooleanGameFunctions$OverPassableTileBoolean()).with("type=\'LAND\'").createLocked(), new String[]{"self.isOverOpenLand"});
      addBooleanType(new LogicBooleanGameFunctions$TagsBoolean(), new String[]{"self.tags", "self.hasTags"});
      addBooleanType(new LogicBooleanGameFunctions$TeamTagBoolean(), new String[]{"self.globalTeamTags", "self.hasGlobalTeamTags"});
      addBooleanType(new LogicBooleanGameFunctions$HasFlagDynamicBoolean(), new String[]{"self.hasFlag"});
      addBooleanType(new LogicBooleanGameFunctions$EnergyBoolean(), new String[]{"self.energy"});
      addBooleanType(new LogicBooleanGameFunctions$EnergyIncludingQueuedBoolean(), new String[]{"self.energyIncludingQueued"});
      addBooleanType((new LogicBooleanGameFunctions$EnergyBoolean()).with("full=true"), new String[]{"self.isEnergyFull"});
      addBooleanType((new LogicBooleanGameFunctions$EnergyBoolean()).with("empty=true"), new String[]{"self.isEnergyEmpty"});
      addBooleanType(new LogicBooleanGameFunctions$TransportingCountBoolean(), new String[]{"self.transportingCount"});
      addBooleanType(new LogicBooleanGameFunctions$TransportingUnitWithTagsBoolean(), new String[]{"self.transportingUnitWithTags"});
      addBooleanType(new LogicBooleanGameFunctions$isTransportUnloading(), new String[]{"self.isTransportUnloading"});
      addBooleanType(new LogicBooleanGameFunctions$PriceCreditsBoolean(), new String[]{"self.priceCredits"});
      addBooleanType(new LogicBooleanGameFunctions$HpBoolean(), new String[]{"self.hp"});
      addBooleanType(new LogicBooleanGameFunctions$MaxHpBoolean(), new String[]{"self.maxHp"});
      addBooleanType(new LogicBooleanGameFunctions$MaxShieldBoolean(), new String[]{"self.maxShield"});
      addBooleanType(new LogicBooleanGameFunctions$MaxEnergyBoolean(), new String[]{"self.maxEnergy"});
      addBooleanType(new LogicBooleanGameFunctions$UnitIdBoolean(), new String[]{"self.id"});
      addBooleanType(new LogicBooleanGameFunctions$TeamIdBoolean(), new String[]{"self.teamId"});
      addBooleanType(new LogicBooleanGameFunctions$TeamDefeatedTechBoolean(), new String[]{"self.teamDefeatedTech"});
      addBooleanType(new LogicBooleanGameFunctions$TeamWipedOutBoolean(), new String[]{"self.teamWipedOut"});
      addBooleanType(new LogicBooleanGameFunctions$TeamVictoryBoolean(), new String[]{"self.teamVictory"});
      addBooleanType(new LogicBooleanGameFunctions$isEnergyRechargingBoolean(), new String[]{"self.isEnergyRecharging"});
      addBooleanType(new LogicBooleanGameFunctions$PositionXBoolean(), new String[]{"self.x"});
      addBooleanType(new LogicBooleanGameFunctions$PositionYBoolean(), new String[]{"self.y"});
      addBooleanType(new LogicBooleanGameFunctions$RotationBoolean(), new String[]{"self.dir"});
      addBooleanType(new LogicBooleanGameFunctions$MaxMoveSpeedBoolean(), new String[]{"self.maxMoveSpeed"});
      addBooleanType(new LogicBooleanGameFunctions$BuiltAmountBoolean(), new String[]{"self.builtAmount"});
      addBooleanType(new LogicBooleanGameFunctions$CompletedBoolean(), new String[]{"self.completed"});
      addBooleanType(new LogicBooleanGameFunctions$ShieldBoolean(), new String[]{"self.shield"});
      addBooleanType(new LogicBooleanGameFunctions$AmmoBoolean(), new String[]{"self.ammo"});
      addBooleanType((new LogicBooleanGameFunctions$AmmoBoolean()).with("empty=true"), new String[]{"self.isAmmoEmpty"});
      addBooleanType(new LogicBooleanGameFunctions$AmmoIncludingQueuedBoolean(), new String[]{"self.ammoIncludingQueued"});
      addBooleanType(new LogicBooleanGameFunctions$ResourceCountBoolean(), new String[]{"self.resource"});
      addBooleanType(new LogicBooleanGameFunctions$QueueSize(), new String[]{"self.queueSize"});
      addBooleanType(new LogicBooleanGameFunctions$NumberOfConnectionsBoolean(), new String[]{"self.numberOfConnections"});
      addBooleanType(new LogicBooleanGameFunctions$NumberOfAttachedUnitsBoolean(), new String[]{"self.numberOfAttachedUnits"});
      addBooleanType(new LogicBooleanGameFunctions$HasParent(), new String[]{"self.hasParent"});
      addBooleanType(new LogicBooleanGameFunctions$HasResourcesBoolean(), new String[]{"self.hasResources"});
      addBooleanType(new LogicBooleanGameFunctions$IsResourceLargerThan(), new String[]{"self.isResourceLargerThan"});
      addBooleanType(new LogicBooleanGameFunctions$KillsBoolean(), new String[]{"self.kills"});
      addBooleanType(new LogicBooleanGameFunctions$TimeAliveBoolean(), new String[]{"self.timeAlive"});
      addBooleanType(new LogicBooleanGameFunctions$LastConvertedBoolean(), new String[]{"self.lastConverted"});
      addBooleanType(new LogicBooleanGameFunctions$CustomTimerBoolean(), new String[]{"self.customTimer"});
      addBooleanType(new LogicBooleanGameFunctions$HasTakenDamage(), new String[]{"self.hasTakenDamage"});
      addBooleanType(new LogicBooleanGameFunctions$IsAttackingBoolean(), new String[]{"self.isAttacking"});
      addBooleanType(new LogicBooleanGameFunctions$IsReversingBoolean(), new String[]{"self.isReversing"});
      addBooleanType((new LogicBooleanGameFunctions$IsOnTeam()).with("team=-1").createLocked(), new String[]{"self.isOnNeutralTeam"});
      addBooleanType(new LogicBooleanGameFunctions$IsControlledByAI(), new String[]{"self.isControlledByAI"});
      addBooleanType(new LogicBooleanGameFunctions$NumberOfUnitsInTeam(), new String[]{"numberOfUnitsInTeam", "self.numberOfUnitsInTeam"});
      addBooleanType((new LogicBooleanGameFunctions$NumberOfUnitsInTeam()).with("greaterThan=0, lessThan=-1"), new String[]{"hasUnitInTeam", "self.hasUnitInTeam"});
      addBooleanType((new LogicBooleanGameFunctions$NumberOfUnitsInTeam()).with("greaterThan=-1, lessThan=1"), new String[]{"noUnitInTeam", "self.noUnitInTeam"});
      addBooleanType((new LogicBooleanGameFunctions$NumberOfUnitsInTeam()).with("neutralTeam=true"), new String[]{"numberOfUnitsInNeutralTeam", "self.numberOfUnitsInNeutralTeam"});
      addBooleanType((new LogicBooleanGameFunctions$NumberOfUnitsInTeam()).with("aggressiveTeam=true"), new String[]{"numberOfUnitsInAggressiveTeam", "self.numberOfUnitsInAggressiveTeam"});
      addBooleanType((new LogicBooleanGameFunctions$NumberOfUnitsInTeam()).with("allTeams=true"), new String[]{"numberOfUnitsInAllTeams", "self.numberOfUnitsInAllTeams"});
      addBooleanType((new LogicBooleanGameFunctions$NumberOfUnitsInEnemyOrAllyTeam()).with("ally=false"), new String[]{"numberOfUnitsInEnemyTeam", "self.numberOfUnitsInEnemyTeam"});
      addBooleanType((new LogicBooleanGameFunctions$NumberOfUnitsInEnemyOrAllyTeam()).with("ally=true"), new String[]{"numberOfUnitsInAllyTeam", "self.numberOfUnitsInAllyTeam", "numberOfUnitsInAllyNotOwnTeam", "self.numberOfUnitsInAllyNotOwnTeam"});
      addBooleanType((new LogicBooleanGameFunctions$GameModeBoolean()).with("nukesEnabled=true").createLocked(), new String[]{"game.nukesEnabled"});
      addBooleanType(new LogicBooleanGameFunctions$GameMapWidthBoolean(), new String[]{"game.mapWidth"});
      addBooleanType(new LogicBooleanGameFunctions$GameMapHeightBoolean(), new String[]{"game.mapHeight"});
      addBooleanType(new LogicBooleanGameFunctions$ThisActionRepeatedCount(), new String[]{"thisActionIndex", "index"});
   }
}
